

export const projectsByCategory = [

  {
    category: 'fullstack',
    label: 'Full Stack Projects',
    projects: [
      {
        id: 'food-delivery',
        title: 'Online Food Delivery System',
        shortDesc: 'A feature-rich food ordering platform with User, Restaurant Owner & Admin panels.',
        description:
          'A comprehensive full-stack food delivery platform built with PHP and MySQL. The system supports three distinct user roles — Customer, Restaurant Owner, and Administrator — each with a dedicated dashboard. Customers can browse menus, place orders, and track delivery status. Restaurant owners manage their menus and incoming orders. The admin oversees the entire platform including users, restaurants, and transactions.',
        technologies: ['PHP', 'MySQL', 'HTML', 'CSS', 'JavaScript'],
        features: [
          'User authentication with role-based access (Customer / Owner / Admin)',
          'Dynamic restaurant and menu management for owners',
          'Real-time order placement, tracking, and status updates',
          'Admin dashboard to monitor users, restaurants, and revenue',
          'Coupon and discount management system',
          'Relational database design with normalized tables',
        ],
        githubUrl: 'https://github.com/kalpshah01/project', 
        liveUrl: null,
        hasVideo: true,
        videoSrc: '/videos/Onlinefooddelivery.mp4',   
        screenshots: [
          '/screenshots/food-delivery-1.png',
          '/screenshots/food-delivery-2.png',
          '/screenshots/food-delivery-3.png',
        ],
        thumbnail: '/screenshots/food-delivery-1.png',
        image: '/images/food-delivery.png',
        accentColor: '#2dd4bf',
        year: '2024-25',
      },
      {
        id: 'hotel-management',
        title: 'Diamond Hotel Management System',
        shortDesc: 'Full hotel management with room booking, billing, and admin controls.',
        description:
          'A complete hotel management system built with PHP and MySQL for Diamond Hotel. The system covers the entire hotel workflow — from room availability and guest check-in/check-out to automated billing and report generation. An admin panel provides full control over room types, staff records, reservations, and financial reports.',
        technologies: ['PHP', 'MySQL', 'HTML', 'CSS', 'JavaScript'],
        features: [
          'Room availability calendar with dynamic booking system',
          'Guest check-in and check-out management',
          'Automated invoice and billing generation',
          'Admin panel for room, staff, and reservation management',
          'Financial reporting and occupancy analytics',
          'Secure login system for staff and admin',
        ],
        githubUrl: 'https://github.com/kalpshah01/thediamoned',
        liveUrl: null,
        hasVideo: true,
        videoSrc: '/videos/TheDiamondhotel.mp4',
        screenshots: [
          '/screenshots/hotel-1.png',
          '/screenshots/hotel-2.png',
          '/screenshots/hotel-3.png',
        ],
        thumbnail: '/screenshots/hotel-1.png',
        image: '/images/hotel-management.png',
        accentColor: '#34d399',
        year: '2026',
      },
      {
        id: 'placement-portal',
        title: 'College Placement Portal',
        shortDesc: 'MCA Semester 2 project — placement management for students and admins.',
        description:
          'A College Placement Portal developed as an MCA Semester 2 project using ASP.NET and SQL Server. The system streamlines the placement process by providing a centralized platform for students to register and apply for jobs, and for placement officers to manage companies, post opportunities, and track student applications. Role-based access ensures secure and organized workflows.',
        technologies: ['ASP.NET', 'C#', 'SQL Server', 'HTML', 'CSS', 'Bootstrap'],
        features: [
          'Student registration and profile management',
          'Job posting and application tracking',
          'Placement officer admin dashboard',
          'Company and recruiter management module',
          'Application status tracking for students',
          'Role-based authentication and access control',
        ],
        githubUrl: 'https://github.com/kalpshah01/handshake',  
        liveUrl: null,
        hasVideo: true,
        videoSrc: '/videos/Collageplacementportal.mp4',
        screenshots: [
          '/screenshots/placement-1.png',
          '/screenshots/placement-2.png',
          '/screenshots/placement-3.png',
        ],
        image: '/images/placement-portal.png',
        accentColor: '#2dd4bf',
        year: '2026',
      },
      {
        id: 'bank-management',
        title: 'Bank Account Management System',
        shortDesc: 'Console-based banking system developed in C — MCA Semester 1 project.',
        description:
          'A console-based Bank Account Management System developed in C as an MCA Semester 1 project. This project demonstrates strong command of structured programming, file handling, and data management techniques in C. It simulates core banking operations such as account creation, deposit, withdrawal, balance enquiry, and transaction history retrieval, all persisted using file I/O.',
        technologies: ['C', 'File Handling', 'Data Structures', 'Structured Programming'],
        features: [
          'Account creation with unique account number generation',
          'Deposit and withdrawal operations with validation',
          'Balance enquiry and mini statement display',
          'Transaction history stored and retrieved via file I/O',
          'Secure customer record management',
          'Applied structured programming and data management concepts',
        ],
        githubUrl: 'https://github.com/kalpshah01/Bank_Account_Management_System', 
        liveUrl: null,
        hasVideo: true,
        videoSrc: '/videos/BankAccount.mp4',
        screenshots: [
          '/screenshots/bank-1.png',
          '/screenshots/bank-2.png',
        ],
        thumbnail: '/screenshots/bank-1.png',
        image: '/images/bank-management.png',
        accentColor: '#6ee7b7',
        year: '2025',
      },
    ],
  },

  {
    category: 'react',
    label: 'React Projects',
    projects: [
      {
        id: 'eye-mouse-tracker',
        title: 'Eye & Mouse Tracker',
        shortDesc: 'Interactive React app that tracks cursor movement with animated eye effects.',
        description:
          'An interactive Eye & Mouse Tracker built with React. The application renders animated eyes on screen that follow the user\'s cursor in real time using DOM mouse-move events. Demonstrates creative use of React state, event listeners, and CSS transforms to build an engaging, interactive UI component.',
        technologies: ['React', 'CSS3', 'React Hooks', 'JavaScript'],
        features: [
          'Real-time cursor tracking with smooth animated eyes',
          'CSS transform-based pupil rotation following mouse position',
          'React useState and useEffect for event listener management',
          'Responsive canvas — works on any screen size',
          'Clean, minimal UI with playful interactive design',
        ],
        githubUrl: 'https://github.com/kalpshah01/EyeMouseTracking-GeminiHackathon',
        liveUrl: 'https://eye-mouse-tracking-gemini-hackathon.vercel.app/',
        hasVideo: true,
        videoSrc: '/videos/eyes-mouse.mp4',
        image: '/images/eye-tracker.png',
        accentColor: '#2dd4bf',
        year: '2026',
      },
      {
        id: 'auth-system',
        title: 'Authentication System',
        shortDesc: 'Secure login & signup system with JWT-based authentication.',
        description:
          'A complete authentication system built with React. Implements user registration, login, and logout with protected routes. JWT tokens are stored securely and validated on each request. The UI provides real-time form validation and clear error messages for a smooth user experience.',
        technologies: ['React', 'JWT', 'React Router', 'CSS3'],
        features: [
          'User registration and login with form validation',
          'JWT-based authentication with token persistence',
          'Protected routes — redirect unauthenticated users',
          'Logout and session management',
          'Responsive, modern UI with error handling',
        ],
        githubUrl: 'https://github.com/kalpshah01/Auth-Api',
        liveUrl: null,
        hasVideo: true,
        videoSrc: '/videos/auth-api.mp4',
        screenshots: [
          '/screenshots/auth-1.png',
          '/screenshots/auth-2.png',
        ],
        thumbnail: '/screenshots/auth-1.png',
        image: '/images/auth-system.png',
        accentColor: '#34d399',
        year: '2026',
      },
      {
        id: 'zomato-api',
        title: 'Zomato API Integration',
        shortDesc: 'Restaurant discovery app using Zomato API with search and filters.',
        description:
          'A React application integrating the Zomato REST API to build a restaurant discovery experience. Users can search for restaurants by city or cuisine, view ratings, price range, and detailed information. Implements debounced search, loading states, and error handling for a smooth experience.',
        technologies: ['React', 'REST API', 'Axios', 'CSS3'],
        features: [
          'Restaurant search by location and cuisine type',
          'Live API integration with loading skeletons',
          'Debounced search input for performance',
          'Detailed restaurant cards with ratings and price range',
          'Fully responsive grid layout',
        ],
        githubUrl: 'https://github.com/kalpshah01/food-API-react',
        liveUrl: null,
        hasVideo: true,
        videoSrc: '/videos/Zomato-APi.mp4',
        screenshots: [
          '/screenshots/zomato-1.png',
          '/screenshots/zomato-2.png',
        ],
        thumbnail: '/screenshots/zomato-1.png',
        image: '/images/zomato-api.png',
        accentColor: '#2dd4bf',
        year: '2026',
      },
      {
        id: 'google-keep',
        title: 'Google Keep Clone',
        shortDesc: 'A notes app that replicates Google Keep with color labels and pin support.',
        description:
          'A feature-complete Google Keep clone built with React. Users can create, edit, delete, and color-code notes. Notes can be pinned to the top and archived. The app uses localStorage for data persistence, ensuring notes are saved between sessions.',
        technologies: ['React', 'LocalStorage', 'CSS3', 'React Hooks'],
        features: [
          'Create, edit, and delete notes with rich text',
          'Color-coded notes with 8 color options',
          'Pin notes to keep important ones at top',
          'Archive and restore notes',
          'Responsive masonry grid layout',
          'Persistent data via localStorage',
        ],
        githubUrl: 'https://github.com/kalpshah01/google-keep-clone',
        liveUrl: 'https://google-keep-clone-murex-three.vercel.app/',
        hasVideo: true,
        videoSrc: '/videos/GoogleKeep.mp4',
        screenshots: [
          '/screenshots/keep-1.png',
          '/screenshots/keep-2.png',
        ],
        thumbnail: '/screenshots/keep-1.png',
        image: '/images/google-keep.png',
        accentColor: '#6ee7b7',
        year: '2026',
      },
      {
        id: 'google-contacts',
        title: 'Google Contact Clone',
        shortDesc: 'Contact management app replicating Google Contacts with full CRUD operations.',
        description:
          'A Google Contacts clone built with React. Users can add, edit, search, and delete contacts. Each contact has fields for name, phone, email, and profile photo. Contacts are stored in localStorage and can be sorted alphabetically.',
        technologies: ['React', 'LocalStorage', 'CSS3', 'React Hooks'],
        features: [
          'Add, edit, and delete contacts with photo support',
          'Real-time search and filter by name or phone',
          'Alphabetical sorting and contact grouping',
          'Persistent data via localStorage',
          'Responsive list and grid view toggle',
        ],
        githubUrl: 'https://github.com/kalpshah01/google-contact',
        liveUrl: 'https://google-contact-dgei.vercel.app/',
        hasVideo: true,
        videoSrc: '/videos/GoogleContact.mp4',
        screenshots: [
          '/screenshots/contacts-1.png',
          '/screenshots/contacts-2.png',
        ],
        image: '/images/google-contacts.png',
        accentColor: '#34d399',
        year: '2026',
      },
      {
        id: 'todo-app',
        title: 'Todo Application',
        shortDesc: 'Advanced todo app with categories, priorities, and drag-and-drop support.',
        description:
          'An advanced Todo application built with React. Supports task creation with priority levels (High, Medium, Low), category tagging, and due dates. Tasks can be reordered via drag-and-drop. Completed tasks are moved to a separate section and all data persists via localStorage.',
        technologies: ['React', 'LocalStorage', 'CSS3', 'React Hooks'],
        features: [
          'Create tasks with priority levels and due dates',
          'Category/tag system for task organization',
          'Mark tasks complete and move to done list',
          'Filter by priority, category, or status',
          'Persistent data via localStorage',
        ],
        githubUrl: 'https://github.com/kalpshah01/Todolist-react',
        liveUrl: null,
        hasVideo: true,
        videoSrc: '/videos/todo-backend.mp4',
        screenshots: [
          '/screenshots/todo-1.png',
          '/screenshots/todo-2.png',
        ],
        thumbnail: '/screenshots/todo-1.png',
        image: '/images/todo-app.png',
        accentColor: '#2dd4bf',
        year: '2026',
      },
      {
        id: 'api-integration',
        title: 'API Integration Projects',
        shortDesc: 'A collection of React mini-apps consuming various public REST APIs.',
        description:
          'A collection of React mini-applications that demonstrate integration with various public REST APIs. Includes a weather app (OpenWeatherMap), a movie browser (TMDB API), a news feed (NewsAPI), and a GitHub profile viewer. Each project showcases proper API handling, loading states, and error boundaries.',
        technologies: ['React', 'REST API', 'Axios', 'CSS3'],
        features: [
          'Weather app with city search using OpenWeatherMap',
          'Movie browser with search and genre filter (TMDB API)',
          'Live news feed with category tabs (NewsAPI)',
          'GitHub profile viewer with repository listing',
          'Consistent loading spinners and error handling across all apps',
        ],
        githubUrl: 'https://github.com/kalpshah01/react-exam',
        liveUrl: null,
        hasVideo: true,
        videoSrc: '/videos/OtherAuth-api.mp4',
        screenshots: [
          '/screenshots/api-1.png',
          '/screenshots/api-2.png',
        ],
        image: '/images/api-integration.png',
        accentColor: '#6ee7b7',
        year: '2026',
      },
    ],
  },

  
  {
    category: 'frontend',
    label: 'Frontend Projects',
    projects: [
      {
        id: 'birthday-website',
        title: 'Birthday Website',
        shortDesc: 'A beautiful animated birthday greeting website with confetti effects.',
        description:
          'A beautifully designed birthday greeting website built with HTML, CSS, and JavaScript. Features animated confetti, a cake with blowing candles interaction, a personalized message section, and a photo gallery. Fully responsive for mobile and desktop.',
        technologies: ['HTML', 'CSS', 'JavaScript', 'CSS Animations'],
        features: [
          'Animated confetti and balloon effects on load',
          'Interactive candle-blowing animation',
          'Personalized message and photo gallery section',
          'Countdown timer to the birthday date',
          'Fully responsive and mobile-friendly',
        ],
        githubUrl: 'https://github.com/kalpshah01/birthday',
        liveUrl: null,
        hasVideo: true,
        videoSrc: '/videos/Birthdy.mp4',
        screenshots: ['/screenshots/birthday-1.png', '/screenshots/birthday-2.png'],
        thumbnail: '/screenshots/birthday-1.png',
        image: '/images/birthday-website.png',
        accentColor: '#2dd4bf',
        year: '2026',
      },
      {
        id: 'netflix-clone',
        title: 'Netflix Clone',
        shortDesc: 'A pixel-perfect Netflix UI clone with movie browsing and responsive layout.',
        description:
          'A Netflix Clone built with HTML, CSS, and JavaScript that replicates the look and feel of the Netflix landing page and browsing interface. Features a hero banner, multiple horizontal movie carousels, hover-preview cards, responsive layout, and a sticky navigation bar — closely matching the original Netflix design.',
        technologies: ['HTML', 'CSS', 'JavaScript', 'Responsive Design'],
        features: [
          'Pixel-perfect Netflix UI hero section with CTA buttons',
          'Horizontal scrolling movie carousels by genre',
          'Movie card hover effect with title and play button overlay',
          'Sticky navigation bar that changes on scroll',
          'Fully responsive — mobile, tablet, and desktop layouts',
          'FAQ accordion section replicating Netflix style',
        ],
        githubUrl: 'https://github.com/kalpshah01/21-Days-JS-Challenge/tree/main/Day-20',
        liveUrl: null,
        hasVideo: true,
        videoSrc: '/videos/netfilx-clone.mp4',
        image: '/images/netflix-clone.png',
        accentColor: '#34d399',
        year: '2026',
      },
      {
        id: 'anniversary-website',
        title: 'Anniversary Website',
        shortDesc: 'A romantic anniversary greeting website with timeline and photo gallery.',
        description:
          'A romantic anniversary website featuring a scrolling timeline of memories, an interactive photo gallery with lightbox, and smooth scroll animations. Built with HTML, CSS, and JavaScript with a warm, elegant color palette.',
        technologies: ['HTML', 'CSS', 'JavaScript', 'CSS Animations'],
        features: [
          'Scrolling memory timeline with photos and captions',
          'Photo gallery with lightbox viewer',
          'Animated heart and particle effects',
          'Smooth scroll reveal animations',
          'Fully responsive design',
        ],
        githubUrl: 'https://github.com/kalpshah01/anniversary_wishes',
        liveUrl: null,
        hasVideo: true,
        videoSrc: '/videos/Anniversy.mp4',
        screenshots: ['/screenshots/anniversary-1.png'],
        thumbnail: '/screenshots/anniversary-1.png',
        image: '/images/anniversary-website.png',
        accentColor: '#6ee7b7',
        year: '2026',
      },
      {
        id: 'landing-pages',
        title: 'Landing Pages',
        shortDesc: 'A collection of professional landing pages for various niches.',
        description:
          'A collection of professionally designed landing pages created for various industries — fitness, tech startup, food delivery, and education. Each page demonstrates modern layout techniques, compelling CTAs, responsive design, and optimized performance.',
        technologies: ['HTML', 'CSS', 'JavaScript', 'Responsive Design'],
        features: [
          'Multiple industry-specific landing page designs',
          'Modern hero sections with gradient and glassmorphism',
          'Sticky navigation with smooth scroll',
          'Animated counters, testimonials, and CTA sections',
          'Fully responsive across all device sizes',
        ],
        githubUrl: 'https://github.com/kalpshah01/figma-to-html',
        liveUrl: null,
        hasVideo: true,
        videoSrc: '/videos/Landingpage.mp4',
        screenshots: ['/screenshots/landing-1.png', '/screenshots/landing-2.png'],
        
        image: '/images/landing-pages.png',
        accentColor: '#c49a2a',   
        year: '2026',
      },
      {
        id: 'js-mini-projects',
        title: 'JavaScript Mini Projects',
        shortDesc: 'A collection of JS mini-apps: calculator, clock, quiz, notes, and more.',
        description:
          'A growing collection of JavaScript mini-projects demonstrating core JS concepts. Includes a digital clock, a scientific calculator, a quiz app with timer, a magic notes app with localStorage, a resume checker, a color picker, and a typing speed tester.',
        technologies: ['HTML', 'CSS', 'JavaScript', 'LocalStorage'],
        features: [
          'Digital clock with timezone support',
          'Scientific calculator with keyboard support',
          'Quiz app with timer and score tracking',
          'Magic Notes with localStorage persistence',
          'Resume keyword checker',
          'Color picker and typing speed tester',
        ],
        githubUrl: 'https://githuhttps://github.com/kalpshah01/21-Days-JS-Challengeb.com/kalpshah01',
        liveUrl: 'https://kalpshhttps://21-days-js-challenge.vercel.app/ah01.github.io/resume_projects/',
        hasVideo: true,
        videoSrc: '/videos/Js-mini.mp4',
        screenshots: ['/screenshots/js-1.png', '/screenshots/js-2.png'],
        thumbnail: '/screenshots/js-1.png',
        image: '/images/js-mini.png',
        accentColor: '#34d399',
        year: '2026',
      },
    ],
  },
];


export const allProjects = projectsByCategory.flatMap((cat) =>
  cat.projects.map((p) => ({ ...p, categoryLabel: cat.label }))
);


export const education = [
  {
    id: '1',
    degree: 'Full Stack Development Course',
    institution: 'Red & White Multimedia Education',
    duration: '11/2025 – Present',
    details: 'Full-stack web development with MERN stack',
  },
  {
    id: '2',
    degree: 'Master of Computer Applications (MCA)',
    institution: 'Sarvajanik College Of Engineering College',
    duration: '07/2025 – Present',
    gpa: '9.91 / 10',
  },
  {
    id: '3',
    degree: 'Bachelor of Computer Applications (BCA)',
    institution: 'SMT.Chandanben.S.Shah BCA College',
    duration: 'June 2022 – March 2025',
    gpa: '9.45 / 10',
  },
  {
    id: '4',
    degree: 'Class XII',
    institution: 'Sardar Patel Higher Secondary School, Gujarat Board',
    duration: '2022',
    percentage: '85%',
  },
  {
    id: '5',
    degree: 'Class X',
    institution: 'Sardar Patel Secondary School, Gujarat Board',
    duration: '2020',
    percentage: '80%',
  },
];

export const experience = [
  {
    id: '1',
    title: 'Teaching Assistant (Technical Team Lead)',
    organization: 'Sardar Patel School',
    duration: '09/2024 – 08/2024',
    months: '2 months',
    description:
      'Led the technical team to train school staff on using smart digital boards and modern classroom technology.',
  },
  {
    id: '2',
    title: 'Web Developer – Intern',
    organization: 'DG Intern Hub',
    duration: '01/2026 – Remote',
    months: '1 month',
    description:
      'This 1-month unpaid internship helped gain valuable hands-on experience, improving my skills and gaining real-world professional practices.',
  },
];

export const skillProgress = [
  { name: 'HTML', percentage: 90 },
  { name: 'CSS', percentage: 85 },
  { name: 'JavaScript', percentage: 75 },
  { name: 'React', percentage: 80 },
  { name: 'PHP', percentage: 70 },
  { name: 'MySQL', percentage: 70 },
  { name: 'Python', percentage: 70 },
];

export const frontendTechs = ['HTML', 'CSS', 'JavaScript', 'React'];
export const backendTechs = ['PHP', 'MySQL', 'Python'];
export const realTimeTechs = ['WebSocket', 'Socket.io', 'Firebase'];
